import './globals.css'

import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'

import { interFont } from '@/configs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={interFont.className}>{children}</body>
    </html>
  )
}

export default RootLayout
